version: '3.8'

services:
  owncloud:
    image: owncloud/server
    ports:
      - "8080:8080"
    volumes:
      - owncloud_data:/mnt/data
    restart: always
    environment:
      - OWNCLOUD_DOMAIN=192.168.1.21:8080
      - OWNCLOUD_TRUSTED_DOMAINS=localhost,192.168.1.21
      - OWNCLOUD_OVERWRITE_CLI_URL=http://192.168.1.21:8080/

  grafana:
    image: grafana/grafana
    ports:
      - "3000:3000"
    restart: always

  influxdb:
    image: influxdb:2.7
    ports:
      - "8086:8086"
    environment:
      - DOCKER_INFLUXDB_INIT_MODE=setup
      - DOCKER_INFLUXDB_INIT_USERNAME=admin
      - DOCKER_INFLUXDB_INIT_PASSWORD=adminpass
      - DOCKER_INFLUXDB_INIT_ORG=myorg
      - DOCKER_INFLUXDB_INIT_BUCKET=telegraf
      - DOCKER_INFLUXDB_INIT_RETENTION=0
      - DOCKER_INFLUXDB_INIT_ADMIN_TOKEN=mytoken
      # - INFLUXDB_DB=telegraf
      #- INFLUXDB_ADMIN_USER=admin
      #- INFLUXDB_ADMIN_PASSWORD=adminpass
      #- DOCKER_INFLUXDB_INIT_ORG=myorg
      #- DOCKER_INFLUXDB_INIT_BUCKET=telegraf
      #- DOCKER_INFLUXDB_INIT_RETENTION=0
      #- DOCKER_INFLUXDB_INIT_ADMIN_TOKEN=mytoken  
    restart: always

volumes:
  owncloud_data:
  influxdb_data:

